package com.eleflow.br.models

object WCities {
  val DATA_INICIAL =  "DATA INICIAL"
  val DATA_FINAL =  "DATA FINAL"
  val REGIAO =  "REGIÃO"
  val ESTADO =  "ESTADO"
  val MUNICIPIO = "MUNICÍPIO"
  val PRODUTO =  "PRODUTO"
  val NUMERO_DE_POSTOS_PESQUISADOS =  "NÚMERO DE POSTOS PESQUISADOS"
  val UNIDADE_DE_MEDIDA =  "UNIDADE DE MEDIDA"
  val PRECO_MEDIO_REVENDA =  "PREÇO MÉDIO REVENDA"
  val DESVIO_PADRAO_REVENDA =  "DESVIO PADRÃO REVENDA"
  val PRECO_MIN_REVENDA =  "PREÇO MÍNIMO REVENDA"
  val PRECO_MAX_REVENDA =  "PREÇO MÁXIMO REVENDA"
  val MARGEM_MEDIA_REVENDA =  "MARGEM MÉDIA REVENDA"
  val COEF_DE_VARIACAO_REVENDA =  "COEF DE VARIAÇÃO REVENDA"
  val PRECO_MEDIO_DISTRIBUICAO =  "PREÇO MÉDIO DISTRIBUIÇÃO"
  val DESVIO_PADRAO_DISTRIBUICAO =  "DESVIO PADRÃO DISTRIBUIÇÃO"
  val PRECO_MIN_DISTRIBUICAO =  "PREÇO MÍNIMO DISTRIBUIÇÃO"
  val PRECO_MAX_DISTRIBUICAO =  "PREÇO MÁXIMO DISTRIBUIÇÃO"
  val COEF_DE_VARIACAO_DISTRIBUICAO =  "COEF DE VARIAÇÃO DISTRIBUIÇÃO"
}
